services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./back-end
    ports:
      - "${APP_PORT}:${APP_PORT}"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      JWT_KEY: ${JWT_KEY}
      APP_PORT: ${APP_PORT}
      POSTGRES_HOST: postgres
      APP_HOST: 0.0.0.0
    depends_on:
      - postgres

  frontend:
    build: ./front-end
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    environment:
      SECRET_KEY: ${SECRET_KEY}
      SERVER_PORT: ${SERVER_PORT}
      BACKEND_PORT: ${BACKEND_PORT}
      BACKEND_HOSTNAME: backend
      APP_HOST: 0.0.0.0
    depends_on:
      - backend

volumes:
  postgres_data: