name: CI/CD Pipeline

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v5
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          architecture: 'x64'
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v4
        with:
          languages: python
      - name: Install backend dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r back-end/requirements.txt
          pip install -r back-end/requirements_test.txt
      - name: Install frontend dependencies
        run: |
          pip install -r front-end/requirements.txt
          pip install -r front-end/requirements_test.txt
      - name: CodeQL Autobuild
        uses: github/codeql-action/autobuild@v4
      - name: CodeQL Analysis
        uses: github/codeql-action/analyze@v4
      
